version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres_db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: spring_app

    working_dir: /app

    volumes:
      - .:/app
      - maven_cache:/root/.m2

    command: mvn spring-boot:run --debug

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_S3_PUBLIC_BASE_URL: ${AWS_S3_PUBLIC_BASE_URL}
      APP_PUBLIC_BASE_URL: ${APP_PUBLIC_BASE_URL}

  pdf_service:
    image: node:20-alpine
    container_name: pdf_service

    working_dir: /app

    volumes:
      - ./pdf-service:/app

    command: sh -c "npm install && npm run build && npm run dev"

    ports:
      - "1336:1336"
volumes:
  postgres_data:
  maven_cache: