version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_db

    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: spring_app

    working_dir: /app

    volumes:
      - .:/app
      - maven_cache:/root/.m2

    command: mvn spring-boot:run --debug

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy
      pdfservice:
        condition: service_healthy

    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DB}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_S3_PUBLIC_BASE_URL: ${AWS_S3_PUBLIC_BASE_URL}
      APP_PUBLIC_BASE_URL: ${APP_PUBLIC_BASE_URL}
      PDF_PUBLIC_BASE_URL: ${PDF_PUBLIC_BASE_URL}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_FROM: ${MAIL_FROM}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_TLS: ${MAIL_TLS}

  pdfservice:
    image: node:20-alpine
    container_name: pdfservice

    working_dir: /app

    volumes:
      - ./pdf-service:/app

    command: sh -c "npm install && npm run build && npm run dev"

    ports:
      - "1336:1336"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:1336/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  frontend:
    image: node:20-alpine
    container_name: frontend

    working_dir: /app

    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

    command: sh -c "npm install && npm run dev -- --host"

    ports:
      - "5173:5173"

    environment:
      VITE_SUPABASE_PROJECT_ID: ${VITE_SUPABASE_PROJECT_ID}
      VITE_SUPABASE_PUBLISHABLE_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_BASE_API: http://localhost:8080/api/

    depends_on:
      - app

volumes:
  mysql_data:
  maven_cache:
  frontend_node_modules: